### ISSUE TITLE
[refactoring] Test Executable Name with Spaces in Path

### ISSUE THREAD

**Issue by theurichde** [theurichde/go-aws-sso#164]
> The executable name provided in the credential process template can include spaces from the file system path.

Referring to #160 

### Implementation
* Enhance Tests to cover cases where executable paths may contain (allowed) special characters and whitespaces

**Comment by rafiramadhana** [comment]
> Enhance Tests to cover cases where executable paths may contain (allowed) special characters and whitespaces

Does _executable_ means the output of `os.Executable()` in `ProcessCredentialProcessTemplate`?

**Comment by theurichde** [comment]
Yes, `os.Executable()` - the test case should ensure, that special characters or whitespaces are put into the final aws_credentials file correctly

**Comment by rafiramadhana** [comment]
> ,that special characters or whitespaces are put into the final aws_credentials file correctly

ok, so we are going to test `WriteAWSCredentialsFile`  in cross-platform envs?

https://github.com/theurichde/go-aws-sso/blob/main/pkg/sso/file_system.go#L53

because at first I thought that we are going to test `ProcessCredentialProcessTemplate` and see the output (i.e. the returned `CredentialsFileTemplate`) when `os.Executable()` returns an exe name with spaces

**Comment by theurichde** [comment]
Hey there @rafiramadhana. Sorry for the ultra late reply. 

> because at first I thought that we are going to test ProcessCredentialProcessTemplate and see the output (i.e. the returned CredentialsFileTemplate) when os.Executable() returns an exe name with spaces

You are right, I was mistaken on that.
